/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/blog/1': RouteRecordInfo<'/blog/1', '/blog/1', Record<never, never>, Record<never, never>>,
    '/blog/2': RouteRecordInfo<'/blog/2', '/blog/2', Record<never, never>, Record<never, never>>,
    '/blog/3': RouteRecordInfo<'/blog/3', '/blog/3', Record<never, never>, Record<never, never>>,
    '/blog/4': RouteRecordInfo<'/blog/4', '/blog/4', Record<never, never>, Record<never, never>>,
  }
}
